baseURL = "https://brunofagno.github.io/bruno1/"
languageCode = "en-us"
title = "Bruno Fagno"
theme = "mediumish-gohugo-theme"
summaryLength = 20
copyright = "Bruno Fagno - Direitos autorais"
enableEmoji = true
publishDir = "docs/"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

#[params]
#  logo = "/images/letrab.png"
#  description ="Meu blog pessoal!"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Bruno Fagno"
  thumbnail = "/images/brunim.png"
  description = "Criador deste blog."

[params.index]
  picture = "/images/brunim.png"
  title = "Bruno Fagno"
  subtitle = "Seja bem-vindo ao meu blog pessoal!"
  mdtext = '''
Sou graduando em estatística pela Universidade Federal do Espírito Santo.\
**Neste blog apresentarei análises estatísticas realizadas nas linguagens R e Python.**
### Vamos lá!
'''
  alertbar = false

[params.social]
  github = "brunofagno"
  #linkedin = "<username>"
  #xing = "<username>"
  #medium = "<username>"
  #twitter = "<username>"
  instagram = "brunofagno"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Sobre mim"
    identifier = "about"
    weight = 200
    url = "/"
#[[menu.main]]
#    name = "Imprint"
#    identifier = "imprint"
#    weight = 200
#    url = "/static/imprint"
